name: Verificar DOU

# Executa todo dia às 10h UTC (7h Brasília)
on:
  schedule:
    - cron: '0 10 * * *'  # 10h UTC = 7h BRT
  workflow_dispatch: # permite rodar manualmente

jobs:
  run-dou:
    runs-on: ubuntu-latest
    env:
      SENHA_IN: ${{ secrets.SENHA_IN }}
      SENHA_APP: ${{ secrets.SENHA_APP }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Rodar script DOU
        run: |
          python test.py
